version: "3.7"
services:
  db:
    container_name: db
    image: hyperonio/bundle-h2-demo:2.0.2
    ports:
      - "8082:8082"
      - "9092:9092"
    networks:
      - hyperon-net

  studio:
    container_name: studio
    image: hyperonio/studio:2.2.2
    environment:
      - HYPERON_DATABASE_URL=jdbc:h2:tcp://db/hyperon.demo
      - HYPERON_DATABASE_DIALECT=h2
      - HYPERON_DATABASE_USERNAME=sa
      - HYPERON_DATABASE_PASSWORD=sa
      - HYPERON_STUDIO_SETUP_PASSWORD-FORCE-CHANGE_ENABLED=false
    ports:
      - "38080:8080"
    depends_on:
      - db
    networks:
      - hyperon-net

  web:
    container_name: demo
    build: .
    environment:
      - HYPERON_DATABASE_URL=jdbc:h2:tcp://db/hyperon.demo
    ports:
      - "48080:8080"
    depends_on:
      - db
    networks:
      - hyperon-net

networks:
  hyperon-net:
    driver: bridge
