version: "3.7"
services:
  db:
    container_name: db
    image: hyperonio/bundle-h2-demo:2.0.4
    ports:
      - "8082:8082"
      - "9092:9092"
    networks:
      - hyperon-net

  studio:
    container_name: studio
    image: decerto/higson-studio:4.0.1
    environment:
      - HIGSON_DATABASE_URL=jdbc:h2:tcp://db/hyperon.demo;NON_KEYWORDS=VALUE
      - HIGSON_DATABASE_DIALECT=h2
      - HIGSON_DATABASE_USERNAME=sa
      - HIGSON_DATABASE_PASSWORD=sa
      - HIGSON_STUDIO_SETUP_PASSWORD_FORCE_CHANGE_ENABLED=false
    ports:
      - "38080:38080"
    depends_on:
      - db
    networks:
      - hyperon-net

  web:
    container_name: demo
    build: .
    environment:
      - HYPERON_DATABASE_URL=jdbc:h2:tcp://db/hyperon.demo
    ports:
      - "48080:8080"
    depends_on:
      - db
    networks:
      - hyperon-net

networks:
  hyperon-net:
    driver: bridge
