spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
hyperon:
  database:
    url: jdbc:h2:./database/hyperon.demo;AUTO_SERVER=TRUE;IFEXISTS=TRUE
    username: sa
    password: sa
    dialect: h2
  dev:
    mode: true
    user: admin
  profile: TELCO

server:
  servlet:
    context-path: /telco-configurator
  port: 8080
